version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=rails_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  demo-web:
    build: .
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    environment:
      - RAILS_ENV=test
      - POSTGRES_HOST=db
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=rails_user
      - POSTGRES_PASSWORD=password
      - RAILS_MASTER_KEY=bf57720c5faebccca8c488f63af57eaf
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_HOST=db
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=rails_user
      - POSTGRES_PASSWORD=password
      - RAILS_MASTER_KEY=bf57720c5faebccca8c488f63af57eaf
    depends_on:
      - db
      - redis
    volumes:
      - app-storage:/rails/storage

volumes:
  postgres_data: {}
  app-storage: {}
